server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: все пути → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # GraphQL → проксируем в API nginx
    location /graphql {
        proxy_pass http://nginx:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # GraphiQL тоже
    location /graphiql {
        proxy_pass http://nginx:80;
        proxy_set_header Host $host;
    }
}
